## Numpy package:
1. Numerical data
2. computations on numerics

In [1]:
import numpy as np

### one dimensional array

In [4]:
a = np.array([1,2,3,4,5])
print(a.ndim)

1


2-Dimensional array


In [5]:
a1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
a1
print(a1.ndim)

2


In [6]:
a1.shape

(3, 3)

In [7]:
a.shape

(5,)

In [20]:
a2 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a2.shape[0])
print(a2.shape[1])
print(a2)

4
3
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


### inserting elements into array dinamically


In [11]:
a3 = np.array([],dtype="int32")

In [16]:
a3 = np.append(a3,int(input()))
a3

12


array([12])

In [17]:
a3 = np.append(a3,[12,13,14,15])
a3


array([12, 12, 13, 14, 15])

### Slicing

In [18]:
print(a3[3])

14


In [19]:
print(a2[1,1])

5


In [21]:
print(a2[2:,:])

[[ 7  8  9]
 [10 11 12]]


In [23]:
print(a2[2:,0:2])

[[ 7  8]
 [10 11]]


### iterate through array


In [28]:
for row in a2:
    print(row)

[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]


In [29]:
for ele in a2.flat:
    print(ele,end=" ")

1 2 3 4 5 6 7 8 9 10 11 12 

In [30]:
np.array(a2.flat)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### indexing with boolean array


In [33]:
arr1 = np.arange(1,21).reshape(5,4)
print(arr1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [36]:
r = (arr1%2 == 0)
type(r)
r

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])