## Numpy package:
1. Numerical data
2. computations on numerics

In [1]:
import numpy as np

### one dimensional array

In [4]:
a = np.array([1,2,3,4,5])
print(a.ndim)

1


2-Dimensional array


In [5]:
a1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
a1
print(a1.ndim)

2


In [6]:
a1.shape

(3, 3)

In [7]:
a.shape

(5,)

In [20]:
a2 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a2.shape[0])
print(a2.shape[1])
print(a2)

4
3
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


### inserting elements into array dinamically


In [11]:
a3 = np.array([],dtype="int32")

In [16]:
a3 = np.append(a3,int(input()))
a3

12


array([12])

In [17]:
a3 = np.append(a3,[12,13,14,15])
a3


array([12, 12, 13, 14, 15])

### Slicing

In [18]:
print(a3[3])

14


In [19]:
print(a2[1,1])

5


In [21]:
print(a2[2:,:])

[[ 7  8  9]
 [10 11 12]]


In [23]:
print(a2[2:,0:2])

[[ 7  8]
 [10 11]]


### iterate through array


In [28]:
for row in a2:
    print(row)

[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]


In [29]:
for ele in a2.flat:
    print(ele,end=" ")

1 2 3 4 5 6 7 8 9 10 11 12 

In [30]:
np.array(a2.flat)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### indexing with boolean array


In [33]:
arr1 = np.arange(1,21).reshape(5,4)
print(arr1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [36]:
r = (arr1%2 == 0)
type(r)
r

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [37]:
arr1[r]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

### Appending array

In [44]:
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(11,20).reshape(3,3)
print(np.vstack((arr1,arr2)))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]


In [46]:
print(np.hstack((arr1,arr2)))

[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]


#### Attributes
1. size
2. itemsize
3. dtype
4. ndim
5. shape

In [51]:
arr = np.arange(1,11).reshape(2,5)
print(arr.size)
print(arr.itemsize)
print(arr.dtype)
print(arr.ndim)
print(arr.shape)

10
4
int32
2
(2, 5)


### Functions:
1. zeros() →  gives an array with all zero as elements
2. ones() →  gives an array with all ones as elements
3. full() →  gives an array with all the give value as elements 
4. eye() →  gives an identical array
5. arange() →  arange(start,stop,step)
6. linspace() →  Generates linearly spaced numbers in the given range --> linspace(start,stop,no.of numbers)
7. reshape() →  reshapes your array to give dimensions.shape should be compatible with the array
8. ravel() →  used to Flatten your array.Gives 1d array

In [53]:
z = np.zeros((3,3),dtype="int32")
z

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [57]:
p = np.ones((3,3),dtype="int32")
p

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [59]:
f = np.full((3,3),"v")
f

array([['v', 'v', 'v'],
       ['v', 'v', 'v'],
       ['v', 'v', 'v']], dtype='<U1')

In [60]:
e = np.eye(3,dtype="int32")
e

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [62]:
l = np.linspace(1,10,5)
l

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [2]:
a = np.arange(1,13,2)
a = a.reshape(2,3)
print(a.ravel())

NameError: name 'np' is not defined

### Functions:
1. min()
2. max()
3. sum()
4. sqrt()
5. std()
6. mean()
7. median()

In [1]:
print(a.sum())
print(a.min())
print(a.max())
print(a.sum(axis=1))
print(a.sum(axis=0))


NameError: name 'a' is not defined

In [77]:
np.sqrt(a)

array([[1.        , 1.73205081, 2.23606798],
       [2.64575131, 3.        , 3.31662479]])

In [78]:
np.median(a)

6.0

In [79]:
np.std(a)

3.415650255319866

### Mathematical Operations:
- +,-,*,/,%

In [93]:
ar1 = np.arange(1,10)
ar2 = np.arange(11,20)
print(ar2+ar1)
print(ar2-ar1)
print(ar2-ar1)
print(ar1*ar2)
print(ar1/ar2)
print(ar1%ar2)

[12 14 16 18 20 22 24 26 28]
[10 10 10 10 10 10 10 10 10]
[10 10 10 10 10 10 10 10 10]
[ 11  24  39  56  75  96 119 144 171]
[0.09090909 0.16666667 0.23076923 0.28571429 0.33333333 0.375
 0.41176471 0.44444444 0.47368421]
[1 2 3 4 5 6 7 8 9]


matrix multiplication:
    

In [101]:
ar3 = np.arange(1,10).reshape(3,3)
ar4 = np.arange(11,20).reshape(3,3)
ar3.dot(ar4)

array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])

Transpose:


In [97]:
ar3.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [102]:
a = np.arange(1,11)

### Applying user defined function:


In [104]:
f = np.vectorize(lambda x : x/(x+1))
f(a)

array([0.5       , 0.66666667, 0.75      , 0.8       , 0.83333333,
       0.85714286, 0.875     , 0.88888889, 0.9       , 0.90909091])